### ISSUE TITLE
Setup a Blog for Reports

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#10]
@sajo25 Grab the contents of this folder and commit them to a gh-pages. This can be a blog where you publicly report updates weekly: 

https://github.com/cannin/graph_neural_network_drug_response/tree/main/docs

the content will show up here: 

https://mil2041.github.io/netboxr

@mil2041 may have to change a setting on the repo.

**Comment by sajo25** [comment]
@mil2041 This is where the blog is (for now): https://sajo25.github.io/netboxr/
