### ISSUE TITLE
Non-Standard Files Found 

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#18]
checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  'annotatedGraph.pdf' 'memb.ebc.txt' 'neighborList.txt' 'network.sif', 'nodeType.txt' 'originalGraph.pdf'

https://github.com/sajo25/netboxr/runs/6895696440?check_suite_focus=true

Probably goes in the Rbuildignore file

**Comment by cannin** [comment]
@sajo25 is this fixed?

**Comment by sajo25** [comment]
@cannin Yes
