### ISSUE TITLE
Use of orphaned gtools? 

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#19]
Requires (indirectly) orphaned package: 'gtools'

@cannin find out what depends on gtools

**Comment by mil2041** [comment]
I think I do not use any function from gplots. In my local mac rstudio, I can successfully finish check netboxr package without import gplots package. I will think about why there is a warnning message for requiring gplots package.

**Comment by sajo25** [comment]
@cannin @mil2041 After [removing gplots and gtools from the DESCRPTION](https://github.com/mil2041/netboxr/commit/9f2eea4230ebc3230ebf8a494f27ab9934e3af3b), the [check](https://github.com/sajo25/netboxr/runs/7135654847?check_suite_focus=true) still fails with the following message: 

> Error: Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.

**Comment by cannin** [comment]
@sajo25 Excellent news! Looks like Ubuntu devel failed, but I think it might be a GitHub Actions issue. Please send a pull request. Also, please start referencing specific issues when you commit so we know how changes align with remaining tasks: 

https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message
