### ISSUE TITLE
Document Output Data

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#32]
@mil2041 For output content as part of geneConnector document the output variables; for example neighborList$oddsRatio. Other variables: 

c("idx", "name", "localDegree", "globalDegree", "pValueRaw", "oddsRatio")

https://github.com/mil2041/netboxr/blob/0fbfb3829bde72c7e834b5bbe17244a442c54dda/R/geneConnector.R#L186

**Comment by mil2041** [comment]
In the 3.3 section of netboxr tutorial document,
https://www.bioconductor.org/packages/release/bioc/vignettes/netboxr/inst/doc/netboxrTutorial.html

=====

# Check the p-value of the selected linker
linkerDF <- results$neighborData
linkerDF[linkerDF$pValueFDR < threshold, ]

##   idx   name localDegree globalDegree    pValueRaw oddsRatio  pValueFDR
## CRK    1712    CRK          11           81 2.392088e-05  1.708732 0.01866731
## IFNAR1 4546 IFNAR1           6           23 4.185496e-05  2.518726 0.01866731
## CBL      20    CBL          14          140 6.505470e-05  1.361057 0.01934293
## GAB1    500   GAB1           8           57 2.483197e-04  1.751122 0.04887827
## CDK6    414   CDK6           5           21 3.008515e-04  2.406906 0.04887827
## PTPN11   84 PTPN11          14          163 3.287776e-04  1.191405 0.04887827

**Comment by mil2041** [comment]
idx:
name: gene name, name of a node in the network
localDegree: number of connections from this node to other nodes in the input of the gene list
globalDegree: number of connections from this node to all other nodes in the underlying graphReduced network. 
pValueRaw: p-value from hypergeometric test
oddsRatio: odds ratio
pValueFDR: adjusted p-value after multiple hypothesis correction
