### ISSUE TITLE
Add weights for module stability

### ISSUE THREAD

**Issue by sajo25** [mil2041/netboxr#36]
Does the addition of weights result in more similar modules across (different) networks?

**Comment by sajo25** [comment]
Below are my results after adding the "useWeights" parameter to the geneConnector function. I haven't made the commit just yet. Please let me know where I should upload the datasets and code I generated for the analysis and testing.

**netbox2010 | ebc | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183611475-1f58710c-57fb-40da-b18c-ea6a4ae20b20.png" width = "400" height = "400">

**netbox2010 | ebc | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183639956-cdb6f9e2-a27c-4a7f-9461-e20b3165f37b.png" width = "400" height = "400">

**netbox2010 | lec | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183611500-d653f99c-f459-4024-8a8f-cec772aafe80.png" width = "400" height = "400">

**netbox2010 | lec | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183639981-efb99468-60d8-4405-9a7e-5734e892f3f9.png" width = "400" height = "400">

**netbox2010 | Louvain | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183497756-19b01e90-ef2b-4509-98b5-3bbb88b112b5.png" width = "400" height = "400">

**netbox2010 | Louvain | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498097-4bf00407-b3ec-4aaa-acef-5548bcddbea7.png" width = "400" height = "400">

**netbox2010 | Leiden | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498243-2082186f-1056-405b-9bf9-04174b8616cf.png" width = "400" height = "400">

**netbox2010 | Leiden | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498266-41690f72-59fa-456c-b12a-e8732ef46c06.png" width = "400" height = "400">

**pathway_commons_v8_reactome | ebc | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183611527-3397fae8-64b1-43d2-ac9c-6ab77169d470.png" width = "400" height = "400">

**pathway_commons_v8_reactome | ebc | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183640017-149799b0-15d9-48e8-8633-f309f3c2b85d.png" width = "400" height = "400">

**pathway_commons_v8_reactome | lec | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183611535-62f38a41-78ff-4c08-b164-7f5c56ec41fd.png" width = "400" height = "400">

**pathway_commons_v8_reactome | lec | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183640032-1ecc1686-a438-4b35-8162-f2da951431ae.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Louvain | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498313-4a1a3536-fb13-4d82-b025-7b9f159d8da5.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Louvain | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498353-0cdc7769-a9fe-43c8-824c-23ae71ae9c5b.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Leiden | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498370-93ed7b64-d206-4444-a59d-101780d95cfd.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Leiden | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498386-ce6d29dd-a0df-41ee-9c93-907bb61da128.png" width = "400" height = "400">

**Comment by cannin** [comment]
@sajo25 I wrote some cluster label remapping code: https://gist.github.com/cannin/cd18814c1fb05469b2ee83c673fdad10 look through it, clean it up, and use it for this issue.

**Comment by sajo25** [comment]
These are my (preliminary) results using the cluster label remapping code. I will double check everything and possibly plot all the networks using only the netbox2010 gene list for more context.

<img src = "https://user-images.githubusercontent.com/28693536/184141179-0a97cb72-1b5b-4434-89f0-55ebb4368f3c.png" width = "500" height = "240">

**Comment by sajo25** [comment]
@cannin @mil2041 Below are results using the cluster label remapping code and only interactions with weight > 700.

<img src = "https://user-images.githubusercontent.com/28693536/184559754-8ead31bc-29bc-4505-a154-73d17f650710.png" width = "500" height = "240">

**Comment by cannin** [comment]
Can you add 1 more columns: 1) how many interactions were available for netboxr, 2) how many interactions were used for the rand index calculation?

**Comment by sajo25** [comment]
**Total number of interactions:**
netbox2010 : 157780 
pathwaycommons : 246590
<img src = "https://user-images.githubusercontent.com/28693536/185393808-5deef7f8-ee63-4b94-ad79-a9fc253df3fe.png" width = "500" height = "240">


**Weights > 700 number of interactions:**
netbox2010 : 89551
pathwaycommons : 77496
<img src = "https://user-images.githubusercontent.com/28693536/185393417-d6259871-44e7-46e6-b1aa-20bc0ce8c19f.png" width = "500" height = "240">

The last column in each table is the number of interactions used to calculate the RI.

**Comment by sajo25** [comment]
**Total number of interactions:**
netbox2010 : 157780 
pathwaycommons : 246590
<img src = "https://user-images.githubusercontent.com/28693536/185393808-5deef7f8-ee63-4b94-ad79-a9fc253df3fe.png" width = "500" height = "240">


**Weights > 700 number of interactions:**
netbox2010 : 89551
pathwaycommons : 77496
<img src = "https://user-images.githubusercontent.com/28693536/185393417-d6259871-44e7-46e6-b1aa-20bc0ce8c19f.png" width = "500" height = "240">

The last column in each table is the number of interactions used to calculate the RI.

**Comment by cannin** [comment]
Can you give me the size of the two networks with ecount(VAR$netboxGraph)?

**Comment by sajo25** [comment]
@cannin 

**Original size:**

netbox2010 graph: 152
pathway_commons graph: 12186


**Size when weights > 700:**

netbox2010 graph: 276 interactions
pathway_commons graph: 913 interactions

Does it make sense that the size of the netbox2010 graph increases?

**Comment by cannin** [comment]
Closing in favor of the expanded attempt #44

**Comment by sajo25** [comment]
I will look into why the size of the netbox2010 graph increases as part of Issue #44
