### ISSUE TITLE
Fix the geneList variable for the Pathway Commons V8

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#37]
Remake the object pathway_commons_v8_reactome.rda with the 517 genelist mentioned in the tutorial and included in the netbox2010.rda

**Comment by sajo25** [comment]
Code:

```
load("~/GitHub/netboxr/data/pathway_commons_v8_reactome.rda")
load("~/GitHub/netboxr/data/netbox2010.rda")
pathway_commons_v8_reactome$geneList <- netbox2010$geneList
save(pathway_commons_v8_reactome, file = "pathway_commons_v8_reactome.rda")
```

[Commit](https://github.com/mil2041/netboxr/commit/796e7d97bde67a5656223c0379e0d4e4b9ab34f9), GitHub Actions [check](https://github.com/sajo25/netboxr/actions/runs/2860539650)
