### ISSUE TITLE
Small issue with code under subsection 10.2 in netboxr tutorial 

### ISSUE THREAD

**Issue by sajo25** [mil2041/netboxr#6]
Hi! I'm going through the netboxr tutorial and a part of the code for subsection 10.2 would not run properly until I made a small modification. In particular, when I would run:

```
cna <- dat$gbm_tcga_pub_cna_consensus
cna <- as.numeric(levels(cna))[cna]
  
mut <- dat$gbm_tcga_pub_mutations
mut <- as.character(levels(mut))[mut]
```

the resulting cna and mut would be a list of NAs. It worked when I changed it to:

```
cna <- as.factor(dat$gbm_tcga_pub_cna_consensus)
cna <- as.numeric(levels(cna))[cna]
  
mut <- as.factor(dat$gbm_tcga_pub_mutations)
mut <- as.character(levels(mut))[mut]
```

Not sure if it's just a problem with my code/device or an actual bug but I wanted to point it out.

**Comment by mil2041** [comment]
Thanks, @sajo25 for reporting this issue. I will further check this issue.

**Comment by sajo25** [comment]
Hi @mil2041, I actually think the modification I made isn't correct so please disregard it, but the issue still stands, I get NA's when I run the original code.

**Comment by sajo25** [comment]
This is no longer relevant as we will rewrite that part of the vignette using a different package.
