### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#7]
@sajo25 As a first task can you add GitHub Actions to the repo. This will help us check new commits: Use this as a template:

https://github.com/sanderlab/tumorcomparer/blob/master/.github/workflows/R-CMD-check.yml

**Comment by sajo25** [comment]
@cannin can this commit go directly to master branch?

**Comment by cannin** [comment]
@sajo25 Yes, the related files should be in a hidden .github folder.
