### ISSUE TITLE
Add igraph Methods that Allow Parameterization of Module Size

### ISSUE THREAD

**Issue by cannin** [mil2041/netboxr#9]
See the following methods: 

* https://igraph.org/r/html/latest/cluster_louvain.html
* https://igraph.org/r/html/latest/cluster_leiden.html

**Comment by cannin** [comment]
@sajo25 as you modify the R functions make sure you update the roxygen; helpful links below: 

* https://support.rstudio.com/hc/en-us/articles/200532317-Writing-R-Package-Documentation
* https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio

**Comment by mil2041** [comment]
The "resolution" parameter in the cluster_louvain() function is the parameter to control the size of the community/ module.

**Comment by mil2041** [comment]
Possible solution 2.
Use "weight" in the network edges as an additional filter to control the sparseness of the connected network and thus affect the detected size of the community/ module. 

We can also add "resolution" and "weight" parameters into geneConnector function.

**Comment by sajo25** [comment]
To add module parametrization features to netboxr, I made updates to the geneConnector function as follows:

`geneConnector <- function(geneList, networkGraph, directed = FALSE
pValueAdj = "BH", pValueCutoff = 0.05,
communityMethod = "ebc",
resolutionParam = 1, weightsInput = NULL,
keepIsolatedNodes = FALSE) { [...]`

`if (communityMethod == "louvain") {`
`message(sprintf("Detecting modules using \"Louvain\" method\n"))`
`community <- cluster_louvain(graphOutput, weights = weightsInput,
resolution = resolutionParam)`
`moduleMembership <- membership(community)`
`}`

`if (communityMethod == "leiden") {`
`message(sprintf("Detecting modules using \"Leiden\" method\n"))`
`community <- cluster_leiden(graphOutput, weights = weightsInput,
resolution = resolutionParam)`
`moduleMembership <- membership(community)`
`} [...] }`

I’ve also made the following additions to the roxygen documentation in that same function:

`#' @param communityMethod string for community detection method
c("ebc","lec", "leiden", "louvain") as described in the details section
(default = "ebc") [...]`
`#' @param resolutionParam numeric value that determines community size,
where higher resolutions leads to more smaller communities (default = 1)`
`#' @param weightsInput numeric vector for edge weights (default = NULL)`

To test whether the function still works, and whether changing the parameters results in the expected outcome (i.e. different community sizes), I reran the example in the vignette using the new community methods and different resolutionParam values as follows:

`results <- geneConnector(geneList = geneList, networkGraph =
graphReduced, directed = FALSE, pValueAdj = "BH", pValueCutoff =
threshold, communityMethod = "leiden", resolutionParam = 2,
keepIsolatedNodes = FALSE)`

The graphs I obtained can be found below:

**Louvain, resolution = 1**
<img src = "https://user-images.githubusercontent.com/28693536/175822369-4a9a2702-e26a-48a4-a9f4-e33a416ac78e.png" width = "400" height = "400">

**Louvain, resolution = 2**
<img src = "https://user-images.githubusercontent.com/28693536/175822380-2ffc2661-c1a0-4a03-b1d9-48ad9cc8c076.png" width = "400" height = "400">

**Louvain, resolution = 3**
<img src = "https://user-images.githubusercontent.com/28693536/175822704-d3239a06-e2b6-426e-a8cf-8bfb3278f332.png" width = "400" height = "400">

**Louvain, resolution = 5**
<img src = "https://user-images.githubusercontent.com/28693536/175822716-0556da05-1ea9-4c1e-89ef-ee673c7ea0b5.png" width = "400" height = "400">

**Louvain, resolution = 10**
<img src = "https://user-images.githubusercontent.com/28693536/175822727-a6af2c56-3d7a-4691-95d6-aaed9c46d686.png" width = "400" height = "400">

**Louvain, resolution = 20**
<img src = "https://user-images.githubusercontent.com/28693536/175822733-f2ad7571-c13c-4023-8bfc-060f62aa23f8.png" width = "400" height = "400">

**Louvain, resolution = 100**
<img src = "https://user-images.githubusercontent.com/28693536/175822879-567cad76-a016-4ce0-bc73-2515ccaa701b.png" width = "400" height = "400">

**Louvain, resolution = 500**
<img src = "https://user-images.githubusercontent.com/28693536/175822965-23c4cc9e-4f13-4a5e-8229-5f3cdd370703.png" width = "400" height = "400">

Using the following R code:

`table(results$moduleMembership$membership)`

I was able to observe that the number of communities does indeed change as the resolution increases (even when it may not be apparent in the graphs), indicating that the parameter is being implemented as expected. The tables for communities (top row) and number of members (bottom row) of the networks generated using resolution values 1, 2, 3, and 5 can be found in the figures below. The maximum number of communities for this network appears to be 72.

**Louvain, resolution = 1**
<img src = "https://user-images.githubusercontent.com/28693536/175823401-a89a3c8f-0df7-486a-9e41-87b280ba8117.png">

**Louvain, resolution = 2**
<img src = "https://user-images.githubusercontent.com/28693536/175823405-26a5f81c-834c-4685-b01b-8c01d0b2b8f6.png">

**Louvain, resolution = 3**
<img src = "https://user-images.githubusercontent.com/28693536/175823407-f86673e1-6174-4c0f-9fbc-e845318eb537.png">

**Louvain, resolution = 5**
<img src = "https://user-images.githubusercontent.com/28693536/175823408-3c2e5b61-b439-4b60-8e1c-f20ce7b1f63b.png">

The Leiden method consistently outputs a network with 72 communities regardless of which resolution parameter is used in the geneConnector function. In line with this, I’m still trying to figure out what may be going wrong. I will most likely try to use the cgsdr data to test this clustering method further.

I have not tested whether the “weights” parameter works as expected, but will do so at a later time point. Lastly, it is important to note that the previously described changes in the netboxr code are currently implemented only in my forked repository, and will only be merged once the GitHub Actions bugs are resolved.

**Comment by cannin** [comment]
@sajo25 with the example network does the Leiden method does the resolution_parameter do anything? 

```
g <- graph.famous("Zachary")
g <- cluster_leiden(g, resolution_parameter=0.06)
```

**Comment by sajo25** [comment]
@cannin @mil2041 As discussed during our previous meeting, I am now trying to introduce the "weights" parameter and test it using the combined_score values from this [dataset](https://stringdb-static.org/download/protein.links.detailed.v11.5/9606.protein.links.detailed.v11.5.txt.gz). I'm having some trouble understanding where and how I can best introduce the weights, since the geneConnector function accepts a list of genes, and not a network. Will the geneConnector function come up with the same network (i.e. same number of interactions) if I only use the gene IDs from the aforementioned dataset as input? Or did I misunderstand the task?

**Comment by sajo25** [comment]
@cannin @mil2041 Below is the code I've written for getting the weights (and mapping the gene IDs, which is takes a long time).
```
library(readr)

# PARAMETERS ----
stringdb_dir <- "C:/Users/s_ara/Downloads/9606.protein.links.detailed.v11.5.txt"
stringdb_dir2 <- "C:/Users/s_ara/Downloads/9606.protein.info.v11.5.txt/"

# DATA ----
## Read Interactions
# From: https://string-db.org/cgi/download?species_text=Homo+sapiens
dat_stringdb <- read_delim(file.path(stringdb_dir, "9606.protein.links.detailed.v11.5.txt"), delim=" ", col_types = cols(
  protein1 = col_character(),
  protein2 = col_character(),
  neighborhood = col_double(),
  fusion = col_double(),
  cooccurence = col_double(),
  coexpression = col_double(),
  experimental = col_double(),
  database = col_double(),
  textmining = col_double(),
  combined_score = col_double()
))
dict_stringdb <- read.table(paste(stringdb_dir2, "9606.protein.info.v11.5.txt", sep = ""), sep ="\t")
stringdb_genes <- dict_stringdb$V2
geneList = stringdb_genes

results <- geneConnector(geneList=geneList,
                        networkGraph=graphReduced,
                        directed=FALSE,
                       pValueAdj="BH",
                       pValueCutoff=threshold,
                       communityMethod="louvain",
                       keepIsolatedNodes=FALSE)

dat_weights = c()
graphTemp_df = as_data_frame(results$netboxGraph)
for (i in 1:nrow(graphTemp_df)) {
  print(i)
  prot1 = graphTemp_df[i,1]
  prot2 = graphTemp_df[i,2]
  prot1 = dict_stringdb[dict_stringdb[,2]==prot1,]$V1
  prot2 = dict_stringdb[dict_stringdb[,2]==prot2,]$V1
  new_weight = dat_stringdb[dat_stringdb[,1]==prot1 & dat_stringdb[,2]==prot2,]$combined_score
  if (length(new_weight) == 0) {
    dat_weights = append(dat_weights, 1)
  } else {
    dat_weights = append(dat_weights, new_weight) 
  }
}
```
I would then use the dat_weights vector as input in the geneConnector function.

**Comment by sajo25** [comment]
@cannin @mil2041 As per our last conversation, I am in the process of making the geneConnector function print a message for community detection methods (ebc and lec) that are incompatible with the "weights" parameter. I noticed that in the igraph manual [cluster_edge_betweenness](https://igraph.org/r/doc/cluster_edge_betweenness.html) and [cluster_leading_eigen](https://igraph.org/r/doc/cluster_leading_eigen.html) both accept edge weights. In the geneConnector function, however, we use edge.betweenness.community and leading.eigenvector.community (which do not accept weights) instead. Is there a reason for this?

**Comment by sajo25** [comment]
Below are my results after adding the "useWeights" parameter to the geneConnector function. I haven't made the commit just yet. Please let me know where I should upload the datasets and code I generated for the analysis and testing.

**netbox2010 | Louvain | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183497756-19b01e90-ef2b-4509-98b5-3bbb88b112b5.png" width = "400" height = "400">

**netbox2010 | Louvain | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498097-4bf00407-b3ec-4aaa-acef-5548bcddbea7.png" width = "400" height = "400">

**netbox2010 | Leiden | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498243-2082186f-1056-405b-9bf9-04174b8616cf.png" width = "400" height = "400">

**netbox2010 | Leiden | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498266-41690f72-59fa-456c-b12a-e8732ef46c06.png" width = "400" height = "400">


**pathway_commons_v8_reactome | Louvain | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498313-4a1a3536-fb13-4d82-b025-7b9f159d8da5.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Louvain | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498353-0cdc7769-a9fe-43c8-824c-23ae71ae9c5b.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Leiden | no weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498370-93ed7b64-d206-4444-a59d-101780d95cfd.png" width = "400" height = "400">

**pathway_commons_v8_reactome | Leiden | weights**

<img src = "https://user-images.githubusercontent.com/28693536/183498386-ce6d29dd-a0df-41ee-9c93-907bb61da128.png" width = "400" height = "400">

**Comment by cannin** [comment]
Closed now resolution parameter should be accepted for the igraph methods
